### ISSUE TITLE
Cannot connect to Neo4J database : com.archimatetool.model.IFeatures cannot be found

### ISSUE THREAD

**Issue by WonderLabWoman** [archi-contribs/database-plugin#104]
Archi version: 4.3.3 on Windows machine,
database-plugin version: 2.2.9

When trying to connect to Neo4J database by pressing the 'check' option (have not tried other databases), I get an error.
consoleLog shows : 
[.....
Caused by: java.lang.ClassNotFoundException: com.archimatetool.model.IFeatures cannot be found by org.archicontribs.database_2.2.9
.....]

Help will be greatly appreciated! :)

**Comment by herve91** [comment]
I'll double check and tell you ASAP

**Comment by herve91** [comment]
It didn't come to my mind yesterday, but the version 2.2.9 of the plugin is not compatible with Archi 4.3.3 as is exports "features" that have been introduced in Archi 4.6.

So you need to upgrade Archi to version 4.6 or 4.7 to use the plugin version 2.2.9.

Best regards
Hervé

**Comment by WonderLabWoman** [comment]
Thank you Hervé, for your quick reply and helpful explanation!
This was also my guess, resulting from my research into the error.  

Could you edit this line in the README.md?
 
"**Archi versions compatibility**
- The v2 of the plugin is compatible with Archi 4.x" 


Would it be possible to use an older version of the plugin?  It may not be possible for me to upgrade Archi. 

Kind regards,
Dominique

**Comment by herve91** [comment]
The line in the readme was added to distinguish the v1 and the v2 branches of my plugin. The former one was made for Archi 3.x and the v2 for Archi 4.x. But I did not anticipate that the structure of the Archimate file would change and I never updated the line.

Yes, you can downgrade the plugin to version version 2.2.1. If you only use the plugin with Neo4J, you do not need to do something else than replacing the plugin, but if you use the plugin with SQL databases, please come back to me and I'll try to help you to downgrade the SQL databases structure.

Alternatively, if you're not in a rush, I can study a way to update my plugin that it is compatible with your version of Archi. It should take 1 or 2 weeks ... After all, it may be of some interest for some other people too and you'll profit from the improvements done since last year.

Best regards
Hervé
