### ISSUE TITLE
The DROP TABLE reference for archi_plugin

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#14]
I notice on all the V2 schema's, there's a drop table reference to a table called "archi_plugin", however, it's not referenced anywhere else in the schema definition, and it doesn't seem to be a V1 --> V2 migration item, as I couldn't see that table defined in the V1 schema's either. Maybe not a bug, but not sure if it's needed.

**Comment by herve91** [comment]
Thas is because the way I used to check the datamodel was using the table "archi_plugin".

But this was before I included the automatic management of the database in my plugin (it is now able to create its table and upgradethem from one version to another). To achieve this, I prefered to change the table name.

This delete is here only to ensure that both tables are not present at the same time.

Best regards
Hervé
