### ISSUE TITLE
Deleted Elements In Archi Model not being reflected into the database

### ISSUE THREAD

**Issue by ricardo-cabral** [archi-contribs/database-plugin#160]
Hello,

Database: Postgres
Plugin Version 4.9.6

I did a cleanup in my model today and I had to delete a lot of  elements from it.

Once I try to export the model updated to the database the elements are not being show in the Deleted Section as you can see below

![image](https://user-images.githubusercontent.com/8196121/216102377-0d299292-f59f-4da4-b4bb-61fa4ffcba99.png)

Doing some investigation, I realized that the DBGuiExportModel class is responsible for controlling the deletion of the elements have some Hasshmap comparing the current Archi Model with the one stored in the database, for example

```
@Getter private HashMap<String, DBMetadata> elementsNotInModel = new HashMap<String, DBMetadata>();
```

Looking at the code below, it is possible to see that a DBMetaData is created in order to check what will be deleted

```
// if the component is not in the model, we create a DBMetadata class and store it in the elementsNotInModel list
					if ( currentComponent == null ) {
						currentComponent = new DBMetadata(currentId);
						this.elementsNotInModel.put(currentId, currentComponent);
						logger.trace("   Getting version of "+currentComponent.getDebugName()+" (is in the database, but not in the model)");
					} else
						logger.trace("   Getting version of "+currentComponent.getDebugName()+" (is in the database and in the model)");
```

If I click in the Export button, the components which  I have removed will appear on it again, as it is the las value stored in the database

When I checked what was happening in the class DBGuiExportModel, I realized that the version != 0 is taken in consideration in order to count that element to be deleted or not, but the code above will always return the version = 0;

```
		// we distinguish the elements new in the database from those deleted from memory
		for ( DBMetadata metadata: this.exportConnection.getElementsNotInModel().values() ) {
			if ( metadata.getInitialVersion().getVersion() != 0 )
				++nbDeleted;        // if the component did exist in the InitialVersion of the model, then it has been deleted from the model
			else
				++nbNewInDb;        // else, the component has been created in the database since the model has been loaded

		}

```

When I add a new line to set the initial version, the plugin starts to show what was deleted, as you can see below:

```
					// if the component is not in the model, we create a DBMetadata class and store it in the elementsNotInModel list
					if ( currentComponent == null ) {
						currentComponent = new DBMetadata(currentId);
THIS LINE ----->			currentComponent.getInitialVersion().set(version, checksum, createdOn, createdBy);
						this.elementsNotInModel.put(currentId, currentComponent);
						logger.trace("   Getting version of "+currentComponent.getDebugName()+" (is in the database, but not in the model)");
					}
```

![image](https://user-images.githubusercontent.com/8196121/216105100-046be28e-2a7a-41fa-91cd-49178ae3c28e.png)

Now the components deleted are not in the model anymore and I can also see that the history is there containing the previous version.

Could you please let me know whether this is an issue or  I am doing something wrong?

Another suggestions is when you query the table elements_in_model and go through all the versions, I did not change that part locally because I do not know the reason and the impact of it, don't you think it would be better to bring only the latest version as the example blow?

Something like this:

```
	SELECT id, name, version, checksum, created_on, created_by, model_id, model_version
	FROM elements
	LEFT JOIN elements_in_model ON element_id = id AND element_version = version and model_version =8
	WHERE id IN (SELECT id FROM elements JOIN elements_in_model ON element_id = id AND element_version = version
				WHERE model_id = 'id-286be3fe876b4da3b39e277758cac0cb' ) 	
	and id = 'id-d9529f29b9d7415bbeb2cfdc0fe65b42'
	ORDER BY id, version, model_version;
```

Best regards,

Ricardo Cabral

**Comment by herve91** [comment]
Hi Ricardo,

I failed to reproduce your issue. Could may follow the folowing steps to understand the delete feature :
    1 - declare a dummy SQLite database in a tmp folder (just to not mess you real database)
    2 - create a new model called test, and add a Business Actor called "me"
<img width="695" alt="image" src="https://user-images.githubusercontent.com/9281982/216133626-145c7b1c-355a-4880-9f56-aa6718ed1420.png">
    3 - save the model in the SQLite database
           --> as expected, the plugn indicates that there is one element and one graphical object to export to the database
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9281982/216134173-dcf8d62d-944f-4c54-a617-46a8d8c2a154.png">
    4 - please export the model

    5 - Then, delete the Business Actor from your model
<img width="695" alt="image" src="https://user-images.githubusercontent.com/9281982/216134556-f7baba03-74c8-4b0e-8171-fe24b1b0627c.png">
    6 - export the model again to the same SQLite database
          --> the plugin indicates correctly that there is one element and one graphical object that were deleted
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9281982/216134825-32e2d6ee-d4d9-40f3-8ddf-7eebbc914dcd.png">


Please let me provide you with more information about this "deleted" column.

It does not indicat the components that the plugin will delete in the database. In fact, I never had time to implement the delete capability in my plugin, so what is exported stay in the database.

You must understand what is done behind the scene: all the components you export in a database will saty forever in the database (because you can always reload an old version of a model). When the model itself is exported to the database, it creates the model in the database (or create a new version of the model if it already exists) and associates all the components present in memory to it.

If a component is no more in memory (because you deleted it), then the component remains in the database. A new version of this component is not created, and the component is not associated to your model anymore.

The delete column in the export window is informative only. Before exporting the model to the database, it checks all the components that were present in the previous version of your model and check if they still are present or not, but this does not influence the export process at all.

Please do not hesitate to ask should you require more information.

**Comment by ricardo-cabral** [comment]
Dear Hervé,

Indeed it worked. I believe my database was corrupted somehow. 

I created a new database and the element appears as deleted.

Apologies for the inconvenience 

Ricardo Cabral
