### ISSUE TITLE
Database import/export plug-in verion 4.9.6

### ISSUE THREAD

**Issue by holgerbranding** [archi-contribs/database-plugin#163]
Hi,

it may well be that I am blind, but I do not manage to export an re-import a very simple model (I enclosed a very short video, link below).

According to the error message I haven't configured a SQL database in the preferences of the import/export plug-in. I read the documentation but didn't find the solution...

I expect that the solution is obvious...

Best regards,
Holger

https://user-images.githubusercontent.com/36538911/225032871-80902a9d-254c-4a88-a0ba-d36b610c12d4.mp4

**Comment by herve91** [comment]
Hi Holger,

Per what I see, you did configured a database called "archimate" in the preferences, and the model export has been completed successfully.

This said, you've got an error message saying that no database is configured to import back your model, and the unique case when this can happen, is when your database is a Neo4J database. The plugin implements export to Neo4J databases but no import.

So, you may configure a relational database (Oracle, SQL Server, PostgreSQL, MySQL or SQLite) in order to be able to import models back.

Hope this helps,

Best regards
Hervé

**Comment by herve91** [comment]
close as the plugin does not allow to import from Neo4J databases
