### ISSUE TITLE
After several export procedure, there are no components on the View

### ISSUE THREAD

**Issue by ZinovyevMaxim** [archi-contribs/database-plugin#18]
Hi, Herve!

I noticed that sometimes for some unknown reason, the components disappear in the View. The components in the model are there but after import, when you open the View there are not any.

1) How to restore display content from previous versions? (Components exist in the model)
2) If select the item popup menu 'get history for ....' the buttons in window for Import/Export are disabled. How coorrect used functionallity

**Comment by herve91** [comment]
Hi Maxim,

I do not understand how view component could disappear.  It never happen to me. I will investigate and let you know.

The only solution I'm thinking about right now is quite technical because it would require to manually edit the database content.
    - in the database plugin preferences, activate the option "show debugging information in the context menu"
   - import the latest version of your model (the one with the empty view) to Archi and note its version number
   - right click on the model to get the model's ID
   - right click on the empty view to get the view's ID and version
   - close your model
   - in database table "views in model", you may find the version of the view imported with your model:
                             SELECT view_version
                             FROM views_in_model
                             WHERE view_id = 'your_view_id'
                             AND model_id = 'your_model_id'
                             AND model_version = your_model_version
   - you then may change the version of the view that will be imported in your model:
                             UPDATE views_in_model
                             SET view_version = old_version_number
                             WHERE view_id = 'your_view_id'
                             AND model_id = 'your_model_id'
                             AND model_version = your_model_version

Then you may import your model and the view will be rolled-back to the version you specified in the database. Modify anything in the view (like any object position) to change its checksum and export your model to the database.

The export procedure should tell you that there is a conflict on your view on the database (because a more recent version of the view exists in the database). Please click on the "export to the database" button and your view (with the components) will be exported to the database.

Please do not forget to backup your database first.

The import / export buttons are grey on the "show history" window because they are on my task list but not yet developed. I will prioritize it. 

Best regards
Hervé

**Comment by ZinovyevMaxim** [comment]
Thanks!!! This method rollback to prevois View version working.

Additional question:
Why Import View from another Model created View without components

**Comment by herve91** [comment]
I've got no idea. This should not happen as when there is an issue during the export process, then the whole export is rolled back.

Nevertheless, I will review my code in detail ...

Best regards
Hervé
