### ISSUE TITLE
Is 2.1 beta 3 still compatible with Archi 4.2?

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#35]
Just wondering if this statement: "It is compatible with the (future) version 4.3 of Archi." means it's only compatible with 4.3, and not 4.2.

**Comment by herve91** [comment]
Hi,

Unfortunately, it is not compatible with 4.2. A Java class has been removed and a new one added in Archi core, so either my plugin is compatible with the old one, either it is compatible with the new one.

Since few days, a professional Java developer is giving me a hand. He is studying a way to create a version that compiles with both 4.2 and 4.3. If not possible, I'll have to provide one plugin for 4.2 and another one for 4.3.

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Ok, thanks for the clarification, Hervé. Much appreciated.

**Comment by herve91** [comment]
Hi,

Before the "universal" version is ready, I release a JAR file that has been compiled against the version 4.2 of Archi.

Please do not hesitate to give it a try and send me all the bugs that you discover.

Please remember that this beta release should not be used on your production database.

Best regards
Hervé
