### ISSUE TITLE
Cannot import elements 

### ISSUE THREAD

**Issue by audreykoz** [archi-contribs/database-plugin#42]
I can't manage to import elements by using the "Import Individual Component" option. I've tried this a variety of ways, but for example, I have a database that I would like to import components from into an empty model. When I go to import components from this model, selecting the class of the element I would like to import into the correct folder type doesn't display any of my elements inside that model in the display box. 
Furthermore, the Category options will freeze if I select an option under "Views" such as "Archimate Views". I either can't leave that option selection screen when clicking "Elements" or selecting "Elements" will not allow me to see the "Views" selection screen again. Switching between various database options seems to aggrevate this behavior. 
Sometimes I can get elements to show up, but this doesn't happen on a predictable basis.
Other info: I'm running Archi version 4.2.0 and the plugin version is 2.0.7. My databases are in SQLite files.

**Comment by herve91** [comment]
The 2.0.7b version of the plugin is effectively very poor in information on how to use the "Import Individual Component" option and the included help files are empty ...

I improved this in the 2.1 version (that is in beta phase at the moment).

The "Import Individual Component" windows allows you to import either an element or a view.

Importing an element:
You need to select the element class(es) you with to import, by a click on a class symbol. The table at the bottom of the window will show up elements of all the classes selected. You can apply a filter on the name of the elements using the filter field. When your mouse stands on an element line in the table, the properties of this element is shown in a tooltip window (if it has got properties of course).

By default, elements that are already in you model or that have got empty names are not shown in the table. You an show them by unselecting the corresponding option below the elements table.

To import elements, you just need to select them in the table and click on the "import" button. To import a single element, you can also double click on it in the elements table.

Importing a view:
Same for view, except that there are only 3 classes (views, canvas and sketches) so they are represented as buttons rather than icons.

Except that, the principe is the same.

Of course, to fill in the elements or views table, a SQL request is sent to the database and the plugin freezes during few seconds until the database returns the requested information. Fut it shouldn't be very long, especially if you're using SQLite.

You may activate the logger part of my plugin to create a log file.

You may also run Archi in console mode (ie. "Archi.exe -consolelog") to showup a log window at the same time as Archi. You'll then have the sames messages from my plugin than the log files and you'll have the error messages of Archi at the same time.

Hope this helps.

Please do not hesitate if you require more assistance.

**Comment by herve91** [comment]
Hi Audrey,

I unfortunately doesn't own a MAC to reproduce your environment. I'm running on Windows at home and at work and never experienced your symptoms with a sqlite database.

But what your description makes me think of is that the database file is locked by another process or cannot be accessed.

Please switch the logger mode to "trace" on the preference page. This will increase the level of details in the log file.

In order to validate that it does not come from your database, you may also go to the preference page, and add a completely new database entry (click on the "new" button, provide an entry name, select the "sqlite" database brand, and fill in the database path to a non existant file, and then click on "save" to register your new database entry). Then, click on the "check" button. the plugin will then indicates that it doesn't find its tables and automatically create them.

Please also ensure that you have got read/write permissions to the database file.

Hope this helps
Best regards
Hervé

**Comment by audreykoz** [comment]
Hey Hervé, 
I've been gone from work for a week so let me get back to you after I've caught up

**Comment by audreykoz** [comment]
Hmm, okay I'm still getting the same freezing behavior. I've enabled trace level logging. Would you like me to send you the log file?

**Comment by audreykoz** [comment]
I did check and I do have read/write access to these files.

**Comment by herve91** [comment]
Yes, you may send me the log file ... in fact, I only need the last lines of the log file to check if there is an error message and at least, if there is no error message at all, try to understand where the plugin hangs.

**Comment by audreykoz** [comment]
So here's the last chunk of the log file: 
<img width="651" alt="screen shot 2018-09-06 at 1 31 59 pm" src="https://user-images.githubusercontent.com/22486586/45177685-421cbf80-b1d9-11e8-8d08-5442f7e15b14.png">
Those last 20 or so lines reflect me attempting to import all elements of the Contract class from a model I have stored in a database. The model I'm attempting to import them into is in the same database. I do know that these Contract elements exist as I've searched the database using other tools, they're just not appearing in the plugin. The plugin appears to be hanging at the "2018-09-06 13:31:45 TRACE 1109:DBGuiImportComponent           - getting elements" line. 
Thanks!

**Comment by herve91** [comment]
Your log files shows a very strange behaviour as the "getting elements" appear 3 times ...

I use 2 different PCs to compile my plugins and some MAC users raised issues on another plugin when it is compiled with one of my PC, but the plugin works file when it is compiled with the other one (even if the code is 100% identical).

So, what I suggest is that you try the latest version of my plugin (the one which is in the test folder, version 2.1 beta 9.6). Even if it is a beta version, it is quite stable and is my release candidate for the 2.1 version that I will release in the coming days.

If you have got the same strange behaviour, I'll be able to re-compile it until it works for you. It will be easier for me than roll backing my dev environment to re-compile the 2.0.7 version.

Best regards
Hervé

**Comment by audreykoz** [comment]
This fixed the problem! Beta version works great:)

**Comment by herve91** [comment]
Meanwhile, I've learnt that plugins work fine on MAC only when version is under the form x.y.z where x, y and z are numbers.

Therefore 2.0.7b for my database plugin or 1.0.7.1 for my specialization plugin conduct to very strange behaviour.

So I close this issue. Please do not hesitate to open a new one if you discover an issue with by beta version.

Best regards
Hervé
