### ISSUE TITLE
Plugin breaking Hints window ?

### ISSUE THREAD

**Issue by KingBain** [archi-contribs/database-plugin#58]
Is detailed a bit more in detail here 
https://forum.archimatetool.com/index.php?topic=631.0

**Comment by Phillipus** [comment]
@herve91 This is because you have your own model factory that extends the EMF objects.

The Hints View parser expects to find a Java Interface like `com.archimatetool.model.IBusinessActor` directly on the object but won't find it on your sub-classes.

I've re-written the Hints API so that it maps the simple class name to the hint text. In the above example, it uses `BusinessActor`. As your sub-classes use the same simple class names as their super-classes this should work.

I've created a new branch in the Archi code called "hints-change". Could you test this plugin against that and let me know?

Phil

**Comment by Phillipus** [comment]
@herve91 BTW - is there a better way to do this rather than extend all EMF objects? Perhaps you could use a delegate class that returns a `DBMetadata` object mapped to the class instance?

**Comment by herve91** [comment]
@KingBain, I'll have a look to solve it.

@Phillipus, I'd be happy to implement a delegate class. Unfortunately, I do not have a clue about what is a delegate class ... I believe I need to improve my Java knowledge :) So, some readings planned for the coming weeks :)

**Comment by Phillipus** [comment]
@herve91 It will be solved with my changes to the Hints View.  :-)

But if you want to change the code so that you don't have to replicate all of the classes you could for example:

nstead of doing this in each class:

```
public DBMetadata getDBMetadata() {
   return this.dbMetadata;
}
```

Have something like:

```
class Helper {
   Hashtable lookuptable...;

   public DBMetadata getgetDBMetadataForObject(Object object) {
      DBMetadata dbm = lookuptable.get(object);
      if(dbm == null) {
         dbm = new DBMetadata(object);
         lookuptable.put(object, dbm );
      }
       return dbm;
    }
}
```

**Comment by herve91** [comment]
I'm not sure to understand, but if I can avoid to replicate all the classes, I will definitively study how it works :)

Thanks a lot :)

**Comment by Phillipus** [comment]
@herve91 What I mean is, I think you have replicated all the classes so you can contain a `DBMetadata` object in each one. If so, you don't actually have to put the `DBMetadata` object _inside_ each object but store the reference to it in a lookup table.

**Comment by herve91** [comment]
oh, that's clever. I never thought about that but it would simplify my code a lot.

Thanks again :)

**Comment by herve91** [comment]
Closed as the update done by Phil solved the issue
