### ISSUE TITLE
Question: MAC version

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#73]
Thanks for the quick fix on the duplication issue!

Our organization is about 50% Mac, do they use the jar under the MAC folder, is the jar in the root folder unified?  The MAC version appears to be the previous release.

Thanks,
Dan

**Comment by herve91** [comment]
Hi Dan,

The MAC version was only a renamed version of the JAR file: I used to add a "v" letter before the version number, but the MAC framework validates the version of the JAR file and this "v" letter conducted to the reject of the plugin by the framework.

Since, I removed this "v" letter thus the JAR file can be directly used on MAC.

I also provided a zip file to accomodate the new plugin installation procedure (from Archi Help / Manage Plug-ins ... menu). Did you try this procedure on your MAC ?

Best regards
Hervé

**Comment by dalman1** [comment]
Not yet, i'll work with my colleagues later this week.

**Comment by herve91** [comment]
As from Archi 4.5 the plugins' installation folder has been moved out from the binaries folder, I do not know where to put it on MAC.

I encourage you to use the new procedure (from Archi Help / Manage Plug-ins ... menu).

Please let me know if it worked on MAC :-)
