### ISSUE TITLE
Failed to resolve target connection for

### ISSUE THREAD

**Issue by edvardmokin** [archi-contribs/database-plugin#95]
Views were successfully exported into DB. 

Now not able to import back and receive an error  - Failed to resolve target connection for  

Archi 4.6
DB plugin version 2.2.7

Screenshot below including trace file
![image](https://user-images.githubusercontent.com/54371319/81335212-3bf97900-9075-11ea-8eac-b762c6cb451d.png)
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4595223/DatabasePlugin.log)

**Comment by herve91** [comment]
Sorry for the very long delay, I thought I did earlier :(

My answer may be too late to be usefull, but I write it anyway for reference.

The way the plugin imports data from the database is:
1. import of folders
2. import of elements
3. import of relationships
3b. resolving relationships (the plugin sets the relationships' source and target once all relationships are imported)
4. import of views
5. import of objects (boxes in views)
6. import of connections (arrows in views)
6b. resolving connexions (the plugin sets the connections' source and target once all connections are imported)

The message you're experiencing means that the plugin fails to set the target for one connection. Of course this shouldn't happen and means that your database has got a consistency issue.

The way you may fix this issue is to enable the "Keep partially imported model in case of error" on the plugin's preferences page and then investigate wich connexion cannot be resolved.
![image](https://user-images.githubusercontent.com/9281982/86329656-bba35e80-bc46-11ea-8c6e-64c3a0df6383.png)

Investigation is not really straight forward as you will have to look at IDs to search for the missing component, either connecting directly to the database, either switching on the plugin's log file and setting the log level to "trace".

Best regards

**Comment by herve91** [comment]
I close this issue as I cannot do more on this one.
